### ISSUE TITLE
How to install? XD

### ISSUE THREAD

**Issue by prodhidden** [keijiro/AICommand#1]

**Comment by Liferocka** [comment]
Yes, please explain How to install! Its odd that allot of these GitHub softwares never have directions.

**Comment by Drigtime** [comment]
1. Clone the repo
2. Open the project in Unity
3. In Unity, configure your Open AI API key as said on the README
4. In Unity, click on "Window" -> "AI Command"
5. Enter your query in the text box and Voilà

**Comment by keijiro** [comment]
I added the FAQ section to README.

**Comment by Liferocka** [comment]
> I added the FAQ section to README.

Thank you.

**Comment by Code-shaker** [comment]
It seems it just works on Windowsmachine, couldn't find it by my Unity Version 2022.2.13f on ubuntu
