### ISSUE TITLE
the tab in the project settings wont show up

### ISSUE THREAD

**Issue by CaseyGamingKing** [keijiro/AICommand#5]
I went in the project settings and there was nothing that had ai in it

**Comment by keijiro** [comment]
- Which Unity version are you using?
- Is there any error in Console?

**Comment by Drifttest** [comment]
I am having the same issue but I know it is user error. Unity 2021.3.21f1
Two errors in console:

Assets/Editor/OpenAIUtil.cs(28,59): error CS1503: Argument 3: cannot convert from 'string' to 'byte[]'

Assets/Editor/OpenAIUtil.cs(28,28): error CS1503: Argument 2: cannot convert from 'string' to 'System.Collections.Generic.List<UnityEngine.Networking.IMultipartFormSection>'

**Comment by keijiro** [comment]
It requires Unity 2022.2 or later. Those error messages are caused by the old API.

I added it to the system requirements on README.
